# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Definition of infra-related environment variables

variables:

  # DEV Environment
  ENVIRONMENT: DEV
  RESOURCE_GROUP: rg-mlops-demo-dev
  LOCATION: southeastasia
  NAMESPACE: chbernardmlopsdemodev
  SERVICECONNECTION_RG: conn-mlops-infra
  SERVICECONNECTION_WS: conn-mlops-aml-dev
  AMLWORKSPACE: aml$(NAMESPACE)
  STORAGEACCOUNT: sa$(NAMESPACE)
  EXTERNALSTORAGEACCOUNT: adbstorageact
  EXTERNALFILESYSTEM: nyc-taxi
  EXTERNALDATASTORENAME: nyc-taxi
  KEYVAULT: kv$(NAMESPACE)
  APPINSIGHTS: ai$(NAMESPACE)
  CONTAINERREGISTRY: cr$(NAMESPACE)
